server:
  port: 80
spring:
  application:
    name: Planer
  datasource:
    url: jdbc:postgresql://localhost:5432/ink
    username:  postgres
    password:  postgres
  jpa:
    #show_sql: true
    hibernate:
      ddl-auto: update
upload : this
